### ISSUE TITLE
semantic tags

### ISSUE THREAD

**Issue by rimmesbe** [bahobab/colmar-academy#3]
I like that you are making use of semantic tags. There are many more to use as well, like in this case there is actually an `<aside>` tag. Here is a good article on semantic tags:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/bahobab/colmar-academy/blob/master/index.html#L159

**Comment by bahobab** [comment]
This issue fixed. Actually, I used the outer article as aside tag. Which I think is more accurate.
Since the css rules are based on class it did not require any other modification.
